client_id = "18535610725-m367q6b7s4ipo9hddl7r46gpt1acvmgp.apps.googleusercontent.com"
client_secret = "YOUR_FULL_CLIENT_SECRET_HERE"
redirect_url = "https://vzd9a9meqhktzhznrmgcux.streamlit.app/"

firebase_api_key = "AIzaSyDjC7tdmpEkpsipgf9r1c3HlTO7C7BZ6Mw"
