[firebase_key]
type = "service_account"
project_id = "screenerproapp"
private_key_id = "513becb60e83672dd34c06295e384fb143747a9c"

# VERY IMPORTANT: keep \n exactly as is
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDhq/p9SWl4iI59\nofv1ZZvzjrg1/+3NuCvF/S8atOGdRzW16uWoCyx0YK7bCrSjoghtODaKXhnCPCFm\nZ0zksdis32KDJe4yWUshbgk8l1aXwdTPqu4eaZkeQYc4G8oIeDesby7vDh6XQW4r\nzfMY3bP540jZXG+cc/rXXwEKVTWyNvLgzsxXJ9MgLLsmeXT03xNSuNu4PkKurjoo\n8Bgo3UJOPxWgGDKngPxMY8mlKaH+94cItgNfXHxUoaEk+HLajO7j1LxHLp7FbfAv\nSN4lJ3eUe69XTn/yy0jIKCmQlU/V/qfnBX9QRMbqMKT2u94ZorZ51N1KE0CgpJcd\n74TdIuT5AgMBAAECggEAB5u2NroeYa9s6mRnK7dQwi3aHQvzVv+yDhtClsppXtWT\nRH5WXst9pLDLxFvAilHAqfn+sLyKbsd7MsohyAYM8YsYdaZ2OOFUzJw6mH3bsAMb\nayLuozzZKjF4XxZkwdNXwSsAcJPPyTauAbEQVJLI6hBVGOrqYmJwnwk3bkNAK7Fp\nWs9bbZG8W34ocT4L1LdrO7xo4i1oOlLvSJqtntKpjvn1y1Oal9y4NfpkhTGDqF05\ntH7Pqf8ZS4B2IlB8ieYAGDvZQ5sdlyTf7TdBvSKMdEQdubPtlWcix3CI1ZEf9HaN\nhyKcP8CUPUTw5dwy4VspY0/wYmQRo7bV4Edc5hLNbwKBgQDxUfbJ+QxQcpzHi4DL\nM8jSbK3yiu/EIadVCYbA6ggLGRDGyMuKxzXnZ5kfJx003BkVCzIgkdJJQXbnWSWw\nbwiaCEAW8vM72SIrVGz+4P8NUX5KNIPlgbaqrhhdQZ6b29prwkqDpV/lQ9i2frgP\nfSEviAj1RR/7QEtesav2XK0vhwKBgQDvZlMzyrXZUTer1u6TEpFdNZDza7koUmGa\ngJE6zQW3253LiN8smfxm5uxTEEOYMYoH5FAibyOCxvUB456FqbsiuD+331b/QCCL\nM9IWQYSEHuPn93DVfmEfzVLovbvXiXasOC3u0pjgRui9xXVTRLwRWKUvaS1uTR48\nSoUdXl9nfwKBgAWTKSpdUIWDQE/zzxPirF8AF7ykrQlQ5ba3M5+9SFZJS/Prq5gX\nJg2kfQsVMj2IYCP2UEAkXkFG++I4UwCScBZu3lwpXKkjSQDLQIFa3UmHem1obSue\nJYQn5XQyEeHz4EXhBSupZF+9g4Ijx0jEUUHx2JMh960sPRGA9UIJvg59AoGBAMEk\novfkEbbUyb9/1lcd4d17fAiH3ohjfo9yLrlr87MUIki1kqifS32RzRRuyLofLaeU\nUfqWA+ZcsgrmI1zfRTWLxQyJydyBVkA4fMSr80fMzD636Xa1UZKgysUvXj9UjkP/\nxz8o9WHsk5WXm0Kk775m8E5B4v9chIpL7P12yC3tAoGALQ1bDVQmj9fHEjCPlJ3E\nbis1a2Kzj7SpCuCkFs7t+DAO1L5VxabcMNiCYL7H68ev1mav6lCKjWp+hxOo36Fm\nRRbbNaprlFBoao+C/lO0N8ko+EK47N0wDC0M66DWmEAKPEczgqym563qKGOx7v8F\ncht4+eDV75avZ/+l8/vvWrY=\n-----END PRIVATE KEY-----\n"

client_email = "firebase-adminsdk-fbsvc@screenerproapp.iam.gserviceaccount.com"
client_id = "103000777586599388394"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc@screenerproapp.iam.gserviceaccount.com"
universe_domain = "googleapis.com"


client_id = "18535610725-m367q6b7s4ipo9hddl7r46gpt1acvmgp.apps.googleusercontent.com"
client_secret = "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"   # Replace **** with your full secret
redirect_url = "http://localhost:8501/"  # For local

# When deployed:
# redirect_url = "https://screenerpro.streamlit.app/"
