

[firebase_key]
type = "service_account"
project_id = "screenerproapp"
private_key_id = "513becb60e83672dd34c06295e384fb143747a9c"

private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDhq/p9SWl4iI59
ofv1ZZvzjrg1/+3NuCvF/S8atOGdRzW16uWoCyx0YK7bCrSjoghtODaKXhnCPCFm
Z0zksdis32KDJe4yWUshbgk8l1aXwdTPqu4eaZkeQYc4G8oIeDesby7vDh6XQW4r
zfMY3bP540jZXG+cc/rXXwEKVTWyNvLgzsxXJ9MgLLsmeXT03xNSuNu4PkKurjoo
8Bgo3UJOPxWgGDKngPxMY8mlKaH+94cItgNfXHxUoaEk+HLajO7j1LxHLp7FbfAv
SN4lJ3eUe69XTn/yy0jIKCmQlU/V/qfnBX9QRMbqMKT2u94ZorZ51N1KE0CgpJcd
74TdIuT5AgMBAAECggEAB5u2NroeYa9s6mRnK7dQwi3aHQvzVv+yDhtClsppXtWT
RH5WXst9pLDLxFvAilHAqfn+sLyKbsd7MsohyAYM8YsYdaZ2OOFUzJw6mH3bsAMb
ayLuozzZKjF4XxZkwdNXwSsAcJPPyTauAbEQVJLI6hBVGOrqYmJwnwk3bkNAK7Fp
Ws9bbZG8W34ocT4L1LdrO7xo4i1oOlLvSJqtntKpjvn1y1Oal9y4NfpkhTGDqF05
tH7Pqf8ZS4B2IlB8ieYAGDvZQ5sdlyTf7TdBvSKMdEQdubPtlWcix3CI1ZEf9HaN
hyKcP8CUPUTw5dwy4VspY0/wYmQRo7bV4Edc5hLNbwKBgQDxUfbJ+QxQcpzHi4DL
M8jSbK3yiu/EIadVCYbA6ggLGRDGyMuKxzXnZ5kfJx003BkVCzIgkdJJQXbnWSWw
bwiaCEAW8vM72SIrVGz+4P8NUX5KNIPlgbaqrhhdQZ6b29prwkqDpV/lQ9i2frgP
fSEviAj1RR/7QEtesav2XK0vhwKBgQDvZlMzyrXZUTer1u6TEpFdNZDza7koUmGa
gJE6zQW3253LiN8smfxm5uxTEEOYMYoH5FAibyOCxvUB456FqbsiuD+331b/QCCL
M9IWQYSEHuPn93DVfmEfzVLovbvXiXasOC3u0pjgRui9xXVTRLwRWKUvaS1uTR48
SoUdXl9nfwKBgAWTKSpdUIWDQE/zzxPirF8AF7ykrQlQ5ba3M5+9SFZJS/Prq5gX
Jg2kfQsVMj2IYCP2UEAkXkFG++I4UwCScBZu3lwpXKkjSQDLQIFa3UmHem1obSue
JYQn5XQyEeHz4EXhBSupZF+9g4Ijx0jEUUHx2JMh960sPRGA9UIJvg59AoGBAMEk
ovfkEbbUyb9/1lcd4d17fAiH3ohjfo9yLrlr87MUIki1kqifS32RzRRuyLofLaeU
UfqWA+ZcsgrmI1zfRTWLxQyJydyBVkA4fMSr80fMzD636Xa1UZKgysUvXj9UjkP/
xz8o9WHsk5WXm0Kk775m8E5B4v9chIpL7P12yC3tAoGALQ1bDVQmj9fHEjCPlJ3E
bis1a2Kzj7SpCuCkFs7t+DAO1L5VxabcMNiCYL7H68ev1mav6lCKjWp+hxOo36Fm
RRbbNaprlFBoao+C/lO0N8ko+EK47N0wDC0M66DWmEAKPEczgqym563qKGOx7v8F
cht4+eDV75avZ/+l8/vvWrY=
-----END PRIVATE KEY-----
"""

client_email = "firebase-adminsdk-fbsvc@screenerproapp.iam.gserviceaccount.com"
client_id = "103000777586599388394"
token_uri = "https://oauth2.googleapis.com/token"

