client_id = "18535610725-m367q6b7s4ipo9hddl7r46gpt1acvmgp.apps.googleusercontent.com"
client_secret = "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"
redirect_url = "https://vzd9a9meqhktzhznrmgcux.streamlit.app/"
google_client_id = "18535610725-m367q6b7s4ipo9hddl7r46gpt1acvmgp.apps.googleusercontent.com"
firebase_api_key = "AIzaSyDjC7tdmpEkpsipgf9r1c3HlTO7C7BZ6Mw"

firebase_api_key = "AIzaSyDjC7tdmpEkpsipgf9r1c3HlTO7C7BZ6Mw"
