google_client_id = "18535610725-as5c93ghnhngcu491shth3htcen2aj1h.apps.googleusercontent.com"
google_client_secret = "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"
firebase_api_key = "AIzaSyDjC7tdmpEkpsipgf9r1c3HlTO7C7BZ6Mw"
